name: squad_quest
description: "The quest to find your squad."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.4
  intl: ^0.19.0
  supabase_flutter: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - .env
    # Add assets from the images directory to the application.
    - assets/images/
