name: 'Publish: Flutter Web Build'

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter Version Management CLI
        uses: flutter-actions/setup-fvm@v1

      - name: Install Flutter SDK
        run: fvm install

      - name: Activate Flutter SDK
        run: fvm use --skip-pub-get

      - name: Get depedencies
        run: fvm flutter pub get

      - name: Setup .env
        run: echo "${{ secrets.FLUTTER_ENV_BASE64 }}" | base64 -d > ./.env

      - name: Build for web
        run: fvm flutter build web --base-href "/SquadQuest/"

      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
