name: 'Publish: Flutter Builds'

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter Version Management CLI
        uses: flutter-actions/setup-fvm@v1

      - name: Install Flutter SDK
        run: fvm install

      - name: Activate Flutter SDK
        run: fvm use --skip-pub-get

      - name: Get depedencies
        run: fvm flutter pub get

      - name: Setup .env
        run: echo "${{ secrets.FLUTTER_ENV_BASE64 }}" | base64 -d > ./.env

      - name: Build for web
        run: fvm flutter build web --base-href "/SquadQuest/"

      - name: Upload web artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

      - name: Build for Android
        if: ${{ github.event_name == 'release' }}
        run: fvm flutter build apk

      - name: Upload APK to release
        if: ${{ github.event_name == 'release' }}
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["build/app/outputs/flutter-apk/app-release.apk"]'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
